// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0DxAQ-yawSX3VSbHb2zpIFF-u-QuAs64',
    appId: '1:706750580614:web:1d6a362f7e7bcab2de8e07',
    messagingSenderId: '706750580614',
    projectId: 'note-46484',
    authDomain: 'note-46484.firebaseapp.com',
    storageBucket: 'note-46484.firebasestorage.app',
    measurementId: 'G-387CJSFTE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpeMgXYl0SBxMcGk7ZliT9KBkiPU6pq6o',
    appId: '1:706750580614:android:3bbd277a917b8831de8e07',
    messagingSenderId: '706750580614',
    projectId: 'note-46484',
    storageBucket: 'note-46484.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATyTh6FCh7N-bXPHIH6849p_k3OuR6Vg0',
    appId: '1:706750580614:ios:a0550232090d3939de8e07',
    messagingSenderId: '706750580614',
    projectId: 'note-46484',
    storageBucket: 'note-46484.firebasestorage.app',
    androidClientId: '706750580614-tj2b72c7sb7nlh1psg5gq0p2c7910e9h.apps.googleusercontent.com',
    iosClientId: '706750580614-lsq1mgrefoq4hs41k4ondepqfkvdr7kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlyproject',
  );
}
